[package]
name = "util"
version = "0.1.0"
edition = "2021"
publish = false

[features]
default = ["eg-allow-unsafe-code", "eg-test-data-generation"]
eg-allow-unsafe-code = []
eg-test-data-generation = []

[dependencies]
anyhow.workspace = true
itertools.workspace = true
num-bigint.workspace = true
num-integer.workspace = true
num-traits.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3 = "0.10"
thiserror.workspace = true

[dev-dependencies]
insta = { version = "1.34.0", features = ["ron"] }
