use std::{borrow::Borrow, fs, path::PathBuf, rc::Rc};

use num_bigint::{BigInt, BigUint};
use serde::{Deserialize, Serialize};
use util::{
    csprng::Csprng,
    z_mul_prime::{ZMulPrime, ZMulPrimeElem},
};

use crate::{
    ballot_encrypting_tool::BallotEncryptingTool,
    election_manifest::{Contest, ContestOption, ElectionManifest},
    fixed_parameters::FixedParameters,
    hash::HValue,
    key::{Ciphertext, PublicKey},
    nizk::ProofRange,
};

pub trait Ballot {
    fn encrypt(&self, nonce: &BigUint) -> Ciphertext;
}

/// A contest option in a pre-encrypted ballot.
#[derive(Debug, Serialize)]
pub struct EncryptedContestSelection {
    /// Vector of ciphertexts used to represent the selection
    pub vote: Vec<CiphertextContestSelection>,

    /// Selection hash
    pub crypto_hash: HValue,

    /// Proof of ballot correctness
    pub proof_ballot_correctness: ProofRange,

    // Proof of satisfying the selection limit
    pub proof_selection_limit: ProofRange,
}

/// A contest in a pre-encrypted ballot.
#[derive(Debug)]
pub struct EncryptedContest {
    /// Label
    pub label: String,

    /// Selection in this contest
    pub selection: EncryptedContestSelection,

    /// Contest hash
    pub crypto_hash: HValue,
}

/// An encrypted ballot.
#[derive(Debug)]
pub struct EncryptedBallot {
    /// Label
    label: String,

    /// Contests in this ballot
    contests: Vec<EncryptedContest>,

    /// Confirmation code
    crypto_hash: HValue,
}

/// An encrypted option in a contest.
#[derive(Debug, Clone)]
pub struct CiphertextContestSelection {
    /// Ciphertext
    pub ciphertext: Ciphertext,

    /// Nonce used to produce the ciphertext
    pub nonce: BigUint,
}

/// Serialize for CiphertextContestSelection
impl Serialize for CiphertextContestSelection {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::ser::Serializer,
    {
        self.ciphertext.clone().serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for CiphertextContestSelection {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        match Ciphertext::deserialize(deserializer) {
            Ok(ciphertext) => Ok(CiphertextContestSelection {
                ciphertext,
                nonce: BigUint::from(0 as u8),
            }),
            Err(e) => Err(e),
        }
    }
}

/// A contest option in a pre-encrypted ballot.
#[derive(Debug, Serialize, Deserialize)]
pub struct PreEncryptedContestSelection {
    /// Label
    pub label: String,

    /// Vector of ciphertexts used to represent the selection
    pub selections: Vec<CiphertextContestSelection>,

    /// Shortcode for this option generated by hash trimming
    pub shortcode: String,

    /// Selection hash
    pub crypto_hash: HValue,
}

/// A contest in a pre-encrypted ballot.
#[derive(Debug, Serialize, Deserialize)]
pub struct PreEncryptedContest {
    /// Label
    pub label: String,

    /// Selections in this contest
    pub selections: Vec<PreEncryptedContestSelection>,

    /// Contest hash
    pub crypto_hash: HValue,
}

/// A pre-encrypted ballot.
#[derive(Debug, Serialize, Deserialize)]
pub struct PreEncryptedBallot {
    /// Label
    label: String,

    /// Contests in this ballot
    contests: Vec<PreEncryptedContest>,

    /// Confirmation code
    crypto_hash: HValue,
}

/// Configuration for generating pre-encrypted ballots.
pub struct PreEncryptedBallotConfig {
    /// Election manifest
    pub manifest: ElectionManifest,
    // ballot_style: BallotStyle,
    /// Election public key
    pub election_public_key: PublicKey,

    /// Whether to encrypt the nonce with the election public key
    pub encrypt_nonce: bool,

    /// Election extended base hash
    pub h_e: HValue,
}

impl PreEncryptedBallot {
    pub fn get_label(&self) -> &String {
        &self.label
    }

    pub fn get_contests(&self) -> &Vec<PreEncryptedContest> {
        &self.contests
    }

    pub fn get_crypto_hash(&self) -> &HValue {
        &self.crypto_hash
    }

    pub fn try_new_with(
        config: &PreEncryptedBallotConfig,
        fixed_parameters: &FixedParameters,
        primary_nonce: &[u8],
    ) -> Option<PreEncryptedBallot> {
        // TODO: Find contests in manifest corresponding to requested ballot style

        // Generate contests

        let label = "Sample Election".to_string();
        let b_aux = "Sample Aux Info".as_bytes();

        let mut success = true;
        let mut contests = Vec::new();
        for contest in &config.manifest.contests {
            match PreEncryptedContest::try_new(
                config,
                primary_nonce.as_ref(),
                &contest,
                fixed_parameters,
            ) {
                Some(c) => contests.push(c),
                None => {
                    success = false;
                    break;
                }
            }
        }

        match success {
            true => {
                let crypto_hash =
                    BallotEncryptingTool::generate_confirmation_code(config, &contests, b_aux);

                println!("Confirmation Code:\t{:?}", crypto_hash);

                Some(PreEncryptedBallot {
                    label,
                    contests,
                    crypto_hash,
                })
            }
            false => None,
        }
    }

    pub fn new(
        config: &PreEncryptedBallotConfig,
        fixed_parameters: &FixedParameters,
        csprng: &mut Csprng,
    ) -> (PreEncryptedBallot, [u8; 32]) {
        loop {
            // Generate primary nonce
            let mut primary_nonce = [0u8; 32];
            (0..32).for_each(|i| primary_nonce[i] = csprng.next_u8());

            match PreEncryptedBallot::try_new_with(config, fixed_parameters, &primary_nonce) {
                Some(ballot) => return (ballot, primary_nonce),
                None => continue,
            }
        }
    }

    pub fn nizkp(
        &self,
        csprng: &mut Csprng,
        fixed_parameters: &FixedParameters,
        config: &PreEncryptedBallotConfig,
        voter_selections: &Vec<Vec<usize>>,
    ) -> (Vec<Vec<Vec<ProofRange>>>, Vec<ProofRange>) {
        assert!(voter_selections.len() == self.contests.len());

        // let zmulp = Rc::new(ZMulPrime::new(fixed_parameters.p.clone()));
        let zmulq = Rc::new(ZMulPrime::new(fixed_parameters.q.clone()));

        let mut proof_ballot_correctness = <Vec<Vec<Vec<ProofRange>>>>::new();
        let mut proof_selection_limit = <Vec<ProofRange>>::new();
        for (i, contest) in self.contests.iter().enumerate() {
            proof_ballot_correctness.push(contest.proof_ballot_correctness(
                csprng,
                fixed_parameters,
                config,
                zmulq.clone(),
            ));
            proof_selection_limit.push(contest.proof_selection_limit(
                csprng,
                fixed_parameters,
                config,
                zmulq.clone(),
                config.manifest.contests[i].selection_limit,
                voter_selections[i].as_slice(),
            ));
        }

        (proof_ballot_correctness, proof_selection_limit)
    }

    pub fn write_to_file(self, path: &PathBuf) {
        fs::write(path, serde_json::to_string(&self).unwrap()).unwrap();
    }

    pub fn new_from_file(self, path: &PathBuf) -> Self {
        serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
    }

    pub fn write_primary_nonce_to_file(path: &PathBuf, nonce: &[u8]) {
        fs::write(path, BigUint::from_bytes_be(nonce).to_str_radix(16)).unwrap();
    }

    pub fn read_primary_nonce_from_file(path: &PathBuf) -> String {
        fs::read_to_string(path).unwrap()
    }
}

impl PreEncryptedContest {
    pub fn get_label(&self) -> &String {
        &self.label
    }

    pub fn get_selections(&self) -> &Vec<PreEncryptedContestSelection> {
        &self.selections
    }

    pub fn get_crypto_hash(&self) -> &HValue {
        &self.crypto_hash
    }

    pub fn try_new(
        config: &PreEncryptedBallotConfig,
        primary_nonce: &[u8],
        contest: &Contest,
        fixed_parameters: &FixedParameters,
    ) -> Option<PreEncryptedContest> {
        let mut modified_contest = contest.clone();
        eprintln!("Contest:\t{:?}", modified_contest.label);

        // TODO: Stop assuming null labels are not included
        // Add labels for null selections
        (0..modified_contest.selection_limit).for_each(|j| {
            modified_contest.options.push(ContestOption {
                label: format!("null{}", j + 1),
            })
        });

        let selection_labels = modified_contest
            .options
            .iter()
            .map(|option| option.label.clone())
            .collect::<Vec<String>>();

        let mut success = true;
        let mut selections = <Vec<PreEncryptedContestSelection>>::new();
        for j in 0..modified_contest.options.len() {
            let selection = PreEncryptedContestSelection::new(
                config,
                primary_nonce,
                &modified_contest.options[j],
                modified_contest.label.borrow(),
                selection_labels.borrow(),
                j,
                selection_labels.len(),
                fixed_parameters,
            );
            success &= BallotEncryptingTool::check_shortcode(&selections, &selection);
            if success {
                selections.push(selection);
            }
        }

        // generate_selection also generates encrypted null selections

        match success {
            true => {
                let crypto_hash = BallotEncryptingTool::generate_contest_hash(
                    config,
                    &modified_contest.label,
                    &selections,
                );

                eprintln!("Contest Hash:\t{:?}", crypto_hash);

                Some(PreEncryptedContest {
                    label: modified_contest.label,
                    selections,
                    crypto_hash,
                })
            }
            false => None,
        }
    }

    pub fn proof_ballot_correctness(
        &self,
        csprng: &mut Csprng,
        fixed_parameters: &FixedParameters,
        config: &PreEncryptedBallotConfig,
        zmulq: Rc<ZMulPrime>,
    ) -> Vec<Vec<ProofRange>> {
        // assert!(voter_selections.len() <= self.selections.len());

        let mut proofs = <Vec<Vec<ProofRange>>>::new();
        for (i, selection) in self.selections.iter().enumerate() {
            proofs.push(selection.proof_ballot_correctness(
                csprng,
                fixed_parameters,
                config,
                i,
                zmulq.clone(),
            ));
        }
        proofs
    }

    pub fn proof_selection_limit(
        &self,
        csprng: &mut Csprng,
        fixed_parameters: &FixedParameters,
        config: &PreEncryptedBallotConfig,
        zmulq: Rc<ZMulPrime>,
        selection_limit: usize,
        voter_selections: &[usize],
    ) -> ProofRange {
        let combined_selection = Self::sum_selection_vector(
            fixed_parameters,
            &self.combine_voter_selections(fixed_parameters, voter_selections),
        );

        ProofRange::new(
            csprng,
            fixed_parameters,
            config,
            zmulq,
            &combined_selection.nonce,
            &combined_selection.ciphertext,
            voter_selections.len(),
            selection_limit,
        )
    }

    pub fn combine_voter_selections(
        &self,
        fixed_parameters: &FixedParameters,
        voter_selections: &[usize],
    ) -> Vec<CiphertextContestSelection> {
        assert!(0 < voter_selections.len() && voter_selections.len() <= self.selections.len());

        let mut selections = <Vec<&Vec<CiphertextContestSelection>>>::new();
        for idx in voter_selections {
            selections.push(&self.selections[*idx].selections);
        }

        let mut combined_selection = selections[0].clone();

        for i in (1..voter_selections.len()) {
            for j in (0..combined_selection.len()) {
                combined_selection[j].ciphertext.alpha = (&combined_selection[j].ciphertext.alpha
                    * &selections[i][j].ciphertext.alpha)
                    % fixed_parameters.p.as_ref();
                combined_selection[j].ciphertext.beta = (&combined_selection[j].ciphertext.beta
                    * &selections[i][j].ciphertext.beta)
                    % fixed_parameters.p.as_ref();
                combined_selection[j].nonce = (&combined_selection[j].nonce
                    + &selections[i][j].nonce)
                    % fixed_parameters.q.as_ref();
            }
        }
        combined_selection
    }

    pub fn sum_selection_vector(
        fixed_parameters: &FixedParameters,
        selection: &Vec<CiphertextContestSelection>,
    ) -> CiphertextContestSelection {
        let mut sum_ct = selection[0].ciphertext.clone();
        let mut sum_nonce = selection[0].nonce.clone();
        for i in 1..selection.len() {
            sum_ct.alpha =
                (&sum_ct.alpha * &selection[i].ciphertext.alpha) % fixed_parameters.p.as_ref();
            sum_ct.beta =
                (&sum_ct.beta * &selection[i].ciphertext.beta) % fixed_parameters.p.as_ref();
            sum_nonce = (&sum_nonce + &selection[i].nonce) % fixed_parameters.q.as_ref();
        }

        CiphertextContestSelection {
            ciphertext: sum_ct,
            nonce: sum_nonce,
        }
    }
}

impl PreEncryptedContestSelection {
    pub fn get_label(&self) -> &String {
        &self.label
    }

    pub fn get_selections(&self) -> &Vec<CiphertextContestSelection> {
        &self.selections
    }

    pub fn get_crypto_hash(&self) -> &HValue {
        &self.crypto_hash
    }

    pub fn new(
        config: &PreEncryptedBallotConfig,
        primary_nonce: &[u8],
        selection: &ContestOption,
        contest_label: &String,
        selection_labels: &Vec<String>,
        j: usize,
        length: usize,
        fixed_parameters: &FixedParameters,
    ) -> PreEncryptedContestSelection {
        let label = selection.label.clone();
        let selections = (0..length)
            .map(|k| {
                let ciphertext: Ciphertext;
                let nonce = BallotEncryptingTool::generate_nonce(
                    config,
                    primary_nonce,
                    contest_label.as_bytes(),
                    selection_labels[j].as_bytes(),
                    selection_labels[k].as_bytes(),
                    fixed_parameters,
                );
                ciphertext = config.election_public_key.encrypt_with(
                    fixed_parameters,
                    &nonce,
                    (j == k) as usize,
                );
                CiphertextContestSelection { ciphertext, nonce }
            })
            .collect::<Vec<CiphertextContestSelection>>();

        let crypto_hash =
            BallotEncryptingTool::generate_selection_hash(config, selections.as_ref());
        let shortcode = BallotEncryptingTool::generate_short_code(crypto_hash);

        eprintln!(
            "Selection Hash for {}:\t{} / Shortcode: {}",
            selection.label, crypto_hash, shortcode
        );

        // Generate pre-encrypted votes for each possible (single) choice
        PreEncryptedContestSelection {
            label,
            selections,
            shortcode,
            crypto_hash,
        }
    }

    pub fn proof_ballot_correctness(
        &self,
        csprng: &mut Csprng,
        fixed_parameters: &FixedParameters,
        config: &PreEncryptedBallotConfig,
        sequence_order: usize,
        zmulq: Rc<ZMulPrime>,
    ) -> Vec<ProofRange> {
        let mut proofs = <Vec<ProofRange>>::new();
        for (i, selection) in self.selections.iter().enumerate() {
            proofs.push(selection.proof_ballot_correctness(
                csprng,
                fixed_parameters,
                config,
                sequence_order == i,
                zmulq.clone(),
            ));
        }
        proofs
    }
}

impl CiphertextContestSelection {
    pub fn proof_ballot_correctness(
        &self,
        csprng: &mut Csprng,
        fixed_parameters: &FixedParameters,
        config: &PreEncryptedBallotConfig,
        selected: bool,
        zmulq: Rc<ZMulPrime>,
    ) -> ProofRange {
        ProofRange::new(
            csprng,
            fixed_parameters,
            config,
            zmulq,
            &self.nonce,
            &self.ciphertext,
            selected as usize,
            1,
        )
    }
}
